---
title: 'R Packages'
permalink: /R Packages/
comments: false
---

## R packages

### [`Require`](https://Require.predictiveecology.org)

### A simple package for reproducible package management in R.

This is an all-in-one package manager that is simple and focused around a single function, `Require`. This is different than other approaches to package management such as `packrat`, `checkpoint`, and `renv` as it focuses on a "script-based" solution to a reproducible work flow. Thus, all packages, version numbering, and sources are contained within an R script.

View on [CRAN](https://cran.r-project.org/package=Require); [GitHub](https://github.com/PredictiveEcology/Require); [Website](https://Require.predictiveecology.org/)

### [`SpaDES`](https://spades.predictiveecology.org)

#### Spatially Explicit Discrete System

Metapackage for implementing a variety of event-based models, with a focus on spatially explicit models. These include raster-based, event-based, and agent-based models. The core simulation components (provided by [`SpaDES.core`](https://spades-core.predictiveecology.org/)) are built upon a discrete event simulation (DES) framework that facilitates modularity, and easily enables the user to include additional functionality by running user-built simulation modules (see also [`SpaDES.tools`](https://spades-tools.predictiveecology.org/)). Included are numerous tools to visualize rasters and other maps (via [`quickPlot`](https://quickplot.predictiveecology.org/)), and caching methods for reproducible simulations (via [`reproducible`](https://reproducible.predictiveecology.org/)). Additional functionality is provided by the [`SpaDES.addins`](https://spades-addins.predictiveecology.org/) and [`SpaDES.shiny`](https://spades-shiny.predictiveecology.org/) packages.

View on [CRAN](https://cran.r-project.org/package=SpaDES); [GitHub](https://github.com/PredictiveEcology/SpaDES); [Website](https://spades.predictiveecology.org)

See also:

-   `SpaDES.addins`: <https://spades-addins.predictiveecology.org>
-   `SpaDES.core`: <https://spades-core.predictiveecology.org/>
-   `SpaDES.shiny`: <https://spades-shiny.predictiveecology.org/>
-   `SpaDES.tools`: <https://spades-tools.predictiveecology.org/>

### [`quickPlot`](https://quickplot.predictiveecology.org)

#### A System of Plotting Optimized for Speed and Modularity

A high-level plotting system, built using `grid` graphics, that is optimized for speed and modularity. This has great utility for quick visualizations when testing code, with the key benefit that visualizations are updated independently of one another.

View on [CRAN](https://cran.r-project.org/package=quickPlot); [GitHub](https://github.com/PredictiveEcology/quickPlot); [Website](https://quickplot.predictiveecology.org)

### [`reproducible`](https://reproducible.predictiveecology.org)

#### A set of tools for R that enhance reproducibility beyond package management.

Built on top of `git2r` and `archivist`, this package aims at making high-level, robust, machine and OS independent tools for making deeply reproducible and reusable content in R. This extends beyond the package management utilites of `packrat` and `checkpoint` by including tools for caching and accessing GitHub repositories.

View on [CRAN](https://cran.r-project.org/package=reproducible); [GitHub](https://github.com/PredictiveEcology/reproducible); [Website](https://reproducible.predictiveecology.org/)

### [`fpCompare`](https://fpcompare.predictiveecology.org)

#### Reliable Comparison of Floating Point Numbers

Comparisons of floating point numbers are problematic due to errors associated with the binary representation of decimal numbers. Despite being aware of these problems, people still use numerical methods that fail to account for these and other rounding errors (this pitfall is the first to be highlighted in Circle 1 of Burns (2012) [The R Inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf)). This package provides new relational operators useful for performing floating point number comparisons with a set tolerance.

View on [CRAN](https://cran.r-project.org/package=fpCompare); [GitHub](https://github.com/PredictiveEcology/fpCompare); [Website](https://fpcompare.predictiveecology.org/)

### [`NetLogoR`](https://NetLogoR.PredictiveEcology.org)

#### A port of NetLogo functions and language to R

`NetLogoR` is an R package which aims to help translating agent-based models built in NetLogo ([Wilensky, 1999](https://ccl.northwestern.edu/netlogo/)) into R or help directly with creating new agent-based models in R following the NetLogo framework.

`NetLogoR` provides the necessary [NetLogo's primitives](https://ccl.northwestern.edu/netlogo/docs/dictionary.html) as well as complementary functions to build agent-based models. A programming guide derived from the [NetLogo's Programming Guide](https://ccl.northwestern.edu/netlogo/docs/programming.html) is available.

This package is under construction and therefore function errors and mismatches with the documentation may occur.

View on [CRAN](https://cran.r-project.org/package=NetLogoR); [GitHub](https://github.com/PredictiveEcology/NetLogoR); [Website](https://NetLogoR.predictiveecology.org/)
