---
layout: post
output:
  html_document:
    keep_md: yes
---
---
layout: post
title: Make a live publications page
author: Eliot McIntire
date: Jan 8, 2016
tags: [Zotero, BibBase, Citations, Publications]
comments: true
---

Creating a live web page with your publications is now easy to do and there are many ways to do so. I will show one that uses [Zotero](https://www.zotero.org/) and [GitHub](https://github.com/).

## Prerequisites

1. [Github page with gh-pages set up](https://pages.github.com/)
2. Zotero database, synced with [zotero.org](https://www.zotero.org/)


## Optional

1. A web redirection so that you don't have to use the default web address: https://username.github.io . I won'd go into this here, but, it may be desireable to use a web address that is not the default.

## Steps

1. Go to [bibBase](https://bibbase.org/)
2. Click on the link to the right of Zotero part way down the page (Generate BibBase page ...)
3. You will have to allow bibbase.org access to your zotero account
4. Click on one of your Collections or Groups
5. If the page is correct, copy the URL at the top in the browser
6. Embed it in a markdown page:

        <script src="https://bibbase.org/show?bib=[URL-OF-BIBTEX-FILE]&jsonp=1"></script>

    where you replace `[URL-OF-BIBTEX-FILE]` with the URL you just copied.
    
7. Sync your gh-pages.
8. Browse to your page to see it in action (*e.g.*, [https://predictiveecology.org/publications/](https://predictiveecology.org/publications/)

If you want a little bit of customization, see [bibBase help](https://bibbase.org/help) for more.
