---
title: 'PhD Opportunity in spatial simulation of caribou landscapes in the Northwest Territories.'
author: Eliot McIntire
date: April 20, 2016
categories: [PhD position, Fire, Caribou, Simulation, R]
---
comments: false
---

As part of a multidisciplinary study of vegetation, fire and permafrost dynamics, the successful applicant will develop spatial simulation models to forecast the abundance and spatial distribution of caribou habitat in relation to climate change, fire and human landuse in the Northwest Territories. The models are to be implemented in SpaDES, a new R package for spatial simulation and individual based modelling. Part of the thesis will involve integration of the team’s research findings, scenario development and the implementation of simulation experiments. However, the student will also be expected to conduct applied research in one related topic (e,g, vegetation dynamics, caribou movement) according to their interest, the results of which would be included as a model component. The qualifications are strong quantitative skills and an interest in spatial simulation independent of disciplinary background. A high level of written communication skills in English is essential.  Programming experience (e.g. in R, Python) would be an asset, but modelling courses are available in the lab. 

We offer a 3yr PhD scholarship at C$23,000/yr. The student will be co-supervised by Steve Cumming, Université Laval, Québec QC and Eliot McIntire, Pacific Forestry Centre, Victoria BC. By preference, the position will be tenable at Laval, with at least one semester as a visiting student at the Pacific Forestry Centre. However, we may be able to accommodate exceptional candidates who prefer to study in Western Canada. There will be opportunities to participate in the 2016 or 2017 summer field season. The position will start September 2016. Applications received before May 9th will receive full consideration.

The language of instruction at Université Laval is French, but theses may be written in English. Québec City is well known for its exceptional outdoor recreational opportunities, natural beauty, historical interest and vibrant cultural life. The francophone cultural environment provides non-francophone students an excellent opportunity to develop or improve French language skills

Applicants should submit by email a short statement of interest, a sample of their scientific writing, a current CV, and the names of three references.  For further information, contact the undersigned: 

Steve Cumming, stevec@sbf.ulaval.ca  
Département des sciences du bois et de la forêt, Université Laval  
Centre d’étude de la forêt

Eliot McIntire, eliot.mcintire@canada.ca  
Pacific Forestry Centre  
Victoria, British Columbia
