---
title: 'New package NetLogoR now on CRAN'
date: February 6, 2018
author: Sarah Bauduin
categories: [R, NetLogoR, SpaDES]
comments: false
---
> v0.3.1 is now available on [CRAN](https://cran.r-project.org/package=NetLogoR).

`NetLogoR` is a R package to help you build raster- and individual-based models in the R environment following the framework of NetLogo (Wilenski 1999).
This package does not require installation of the original `NetLogo` software; it is a translation into the R language of the structure and functions of `NetLogo`.
`NetLogoR` provides you classes to define raster cell ("patches") and moving individual ("turtles") objects as well as the R translation of `NetLogo` functions and other complementary ones to build such models.
This package allows you to benefit of the fast and easy coding phase from the highly developed `NetLogo` structure and functions, coupled with the versatility and speed of the R software.
The use of the `SpaDES` package complements well `NetLogoR` by providing useful functions, such as for model visualization.

For a complete list of changes, see [the package's NEWS file](https://raw.githubusercontent.com/PredictiveEcology/NetLogoR/master/NEWS.md).

### Websites

**`NetLogoR` package:** [https://NetLogoR.PredictiveEcology.org](https://NetLogoR.PredictiveEcology.org)

## Installation

**Install development libraries:** building packages from source requires the appropriate development libraries for your operating system.

- *Windows:* install [Rtools](https://cran.r-project.org/bin/windows/Rtools/).
- *macOS:* install Xcode commandline tools from the terminal: `xcode-select install`.
- *Debian/Ubuntu Linux:* ensure `r-base-dev` is installed.

See [here](https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites) for more details.

### Current stable release

**Install from CRAN:**

```r
install.packages("NetLogoR")
```

**Install from GitHub:**

```r
#install.packages("devtools")
library("devtools")
install_github("PredictiveEcology/NetLogoR", dependencies = TRUE) # stable
```

### Development version (unstable)

**Install from GitHub:**

```r
#install.packages("devtools")
library("devtools")
install_github("PredictiveEcology/NetLogoR", ref = "development", dependencies = TRUE) # unstable
```

## Reporting bugs

Bug reports should be reported via the package's GitHub site:

[https://github.com/PredictiveEcology/NetLogoR/issues](https://github.com/PredictiveEcology/NetLogoR/issues)
