---
title: "Our transition to `terra` from `raster`"
author: "Ceres Barros"
date: 07-03-2024
categories:
  - R
  - spatial
comments: false
---

We have been asked multiple times how we are "dealing with the
transition from `raster` to `terra`". The answer is, somewhat painfully
and more slowly than we had hoped for.

Much of what we do involves manipulating spatial objects (raster or
vector data) be it for data extraction (e.g., extracting data for
statistical modelling), results production (e.g., outputting results
spatially) or visualisation (e.g., making maps) and our packages and
SpaDES modules were deeply intertwined with the `raster` and `sp`
packages.

We have started the transition more than a year ago and still haven't
finished. Part of the reason why this takes so long is because we are
attempting to keep backwards compatibility. Which take us to the purpose
of this post.

Our advice to others in the same transition journey as us:

-   Try to keep backwards compatibility. Many `terra` functions allow
    passing `Raster*` class objects. Where they don't, make your own
    function wrappers to deal with this. We have a few in the
    `reproducible` and `LandR` (on
    [GitHub](https://github.com/PredictiveEcology/LandR)) packages (see
    table bellow)

-   Test. A LOT.

That's all really.

Below is a lit of `raster` to `terra` (or other packages) function
equivalencies that may be useful. Note that these are likely to change
as `terra` and other packages evolve.

See also the description of [`terra`
methods](https://rspatial.github.io/terra/reference/terra-package.html#xxviii-new-method-names-1)
for more useful information.

<table>
<tbody>
<tr class="odd">
<td><p><strong><code>raster</code> package</strong></p></td>
<td><p><strong><code>terra</code> or other packages</strong></p></td>
</tr>
<tr class="even">
<td><p><code>ras[]</code></p></td>
<td><p><code>as.vec t o r(ras[])as.vector(values(ras))</code></p></td>
</tr>
<tr class="odd">
<td><p><code>compareCRS</code></p></td>
<td><p>For now,<br />
<code>LandR::.compareCRS</code> – only 2 rasters<br />
<code>LandR::.compareRas</code> – multiple rasters</p></td>
</tr>
<tr class="even">
<td><p><code>maxValue</code>, <code>minValue</code></p></td>
<td><p><code>minmax</code> or<br />
<code>reproducible::minFn</code>,
<code>reproducible::maxFn</code></p></td>
</tr>
<tr class="odd">
<td><p><code>compareRaster</code></p></td>
<td><p><code>terra::compareGeom</code> – more sensitive than
<code>st_crs(x) == st_crs(y)</code> and returns false negatives in many
situations.<br />
<br />
Alternatives are:<br />
<code>sf::st_crs(x) == s f::st_crs(y)LandR::.compareRas</code></p></td>
</tr>
<tr class="even">
<td><p><code>getValues</code></p></td>
<td><p><code>SpatRaster[]</code> returns a matrix, even if it is just
one layer; <code>RasterLayer[]</code> returns a vector;
<code>RasterStack[]</code> returns a matrix<br />
<br />
For consistency, use:<br />
<code>reproducible::values2</code><br />
which replicates the old
<code>RasterLayer</code>/<code>RasterStack</code> behaviour of vector if
1 layer, matrix if &gt; 1 layer, using internally:<br />
<code>terra:: v a lues(ras, mat = nlyr(ras) &gt; 1)</code> if
<code>ras</code> is a <code>RasterLayer</code><br />
<br />
</p></td>
</tr>
<tr class="odd">
<td><p><code>setValues</code></p></td>
<td><p><code>ras[] &lt;-</code></p></td>
</tr>
<tr class="even">
<td><p><code>extract</code>, <code>mask</code>, <code>ncell</code>,
<code>cover</code></p></td>
<td><p>Same function names in <code>terra</code>, all compatible with
<code>RasterLayer</code> and <code>RasterStack</code></p></td>
</tr>
<tr class="odd">
<td><p><code>raster(ras)</code></p></td>
<td><p>Used to create a template raster.</p>
<p><code>terra</code> equivalent is:<br />
<code>rast(ras)</code></p>
<p><code>reproducible::rasterRead</code> can use either, depending on
value of <code>getO p t ion("reproducible.rasterRead")</code></p></td>
</tr>
<tr class="even">
<td><p><code>raster(filepath)</code></p></td>
<td><p>Used to load a raster from a file.</p>
<p><code>terra</code> equivalent is <code>rast(filepath)</code></p>
<p><code>reproducible::rasterRead</code> can use either, depending on
value of <code>getO p t ion("reproducible.rasterRead")</code></p></td>
</tr>
<tr class="odd">
<td><p><code>layerNames</code></p></td>
<td><p><code>names</code></p></td>
</tr>
<tr class="even">
<td><p><code>extent</code></p></td>
<td><p><code>terra::ext</code> – compatible with
<code>RasterLayer</code> and <code>RasterStack</code></p></td>
</tr>
<tr class="odd">
<td><p><code>res</code></p></td>
<td><p><code>terra::res</code> – compatible with
<code>RasterLayer</code> and <code>RasterStack</code></p></td>
</tr>
<tr class="even">
<td><p><code>nlayers</code></p></td>
<td><p><code>length(names(ras))</code> or <code>terra::nlyr</code>; new
transition function <code>reproducible::nlayers2</code> works with
either <code>RasterLayer</code> or <code>SpatRaster</code></p></td>
</tr>
<tr class="odd">
<td><p><code>as.integer(ras)</code> doesn’t work for
<code>SpatRaster</code> … this also doesn’t work:<br />
<code>ras[] &lt;- as.integer(ras[])</code></p></td>
<td><p><code>ras &lt;- LandR::asInt(ras)</code> works on
<code>RasterLayer</code> or <code>SpatRaster</code></p>
<p><code>LandR::isInt</code> # the equivalent for
<code>is.integer</code><br />
<br />
</p></td>
</tr>
<tr class="even">
<td><p><code>setColors</code></p></td>
<td><p>See <code>terra::coltab</code><br />
<br />
</p></td>
</tr>
<tr class="odd">
<td><p><code>subs</code></p></td>
<td><p><code>terra::subst</code> – but arguments are different</p></td>
</tr>
<tr class="even">
<td><p><code>fasterize::fasterize</code></p></td>
<td><p>No equivalent for <code>SpatVector</code> objects yet.</p>
<p>Use <code>terra::rasterize</code> but this appears to be slow at the
moment. sf objects may need to be converted to a temporary
<code>SpatVector</code></p></td>
</tr>
<tr class="odd">
<td><p><code>SpaDES.core::Plots(ras)</code></p></td>
<td><p>Use</p>
<p><code>SpaDES.core::Plo t s (ras, fn = LandR::plotRast, …)</code>
available in LandRdevelopment</p></td>
</tr>
<tr class="even">
<td><p><code>quickPlot::Plot(ras)</code></p></td>
<td><p><code>quickPlot::Plot(ras)</code> – accepts
<code>SpatRaster</code></p></td>
</tr>
<tr class="odd">
<td><p><code>raster::dataType</code></p></td>
<td><p>Equivalent in <code>terra</code> is <code>datatype</code> (notice
different capitalization)</p>
<p><code>reproducible::dataType2</code> works on
<code>RasterLayer</code> and <code>SpatRaster</code></p></td>
</tr>
<tr class="even">
<td><p><code>xyFromCell</code></p></td>
<td><p><code>terra::xyFromCell(..., cell)</code> does not accept (unlike
<code>r aster::xyFromCell(..., cell)</code>)<br />
Passing <code>as.vector(cell)</code> will work with
<code>RasterLayer</code> and <code>SpatRaster</code></p></td>
</tr>
<tr class="odd">
<td><p><code>clump()</code></p></td>
<td><p><code>patches()</code></p></td>
</tr>
<tr class="even">
<td><p><code>filename()</code></p></td>
<td><p>Equivalent in <code>terra</code> is <code>sources()</code><br />
<code>reproducible::Filenames()</code> works on either
<code>RasterLayer</code> or <code>SpatRaster</code></p></td>
</tr>
</tbody>
</table>
