list(
  .progress = list(type = NA, interval = NA),
  .globals = list(),
  dataCastor = list (dbName='castor',
                     saveCastorDB = FALSE,
                     sqlite_dbname = "stsm_compare_noroads_noblocks",
                     useCastorDB = "R/scenarios/comparison_stsm/stsm_compare_noroads_noblocks_castordb.sqlite",
                     nameBoundaryFile = "castor_stsm_compare.bounds_tsa99", 
                     nameBoundaryColumn = "tsa_name", 
                     nameBoundary = "tsa99", 
                     nameBoundaryGeom = 'wkb_geometry',
                     nameCompartmentRaster = "castor_stsm_compare.rast_bounds_tsa99", 
                     nameCompartmentTable = "castor_stsm_compare.vat_bounds_tsa99", 
                     nameMaskHarvestLandbaseRaster = 'castor_stsm_compare.rast_thlb', 
                     nameZoneTable = "castor_stsm_compare.constraints", 
                     nameYieldsRaster = "castor_stsm_compare.rast_ycid_vdyp", 
                     nameYieldTable = "castor_stsm_compare.vdyp", 
                     nameYieldsTransitionRaster = "castor_stsm_compare.rast_ycid_tipsy", 
                     nameYieldTransitionTable = "castor_stsm_compare.tipsy", 
                     nameForestInventoryRaster = "castor_stsm_compare.rast_vri_id", 
                     nameForestInventoryKey = "vri_fid", 
                     nameForestInventoryTable = "castor_stsm_compare.vri",
                     nameForestInventoryAge = "proj_age_1",  
                     nameForestInventoryHeight = "proj_ht_1",
                     nameForestInventoryCrownClosure = "cr_closure",                             
                     nameForestInventoryTreed = "bclcs_lv_2",
                     nameForestInventorySiteIndex = "site_index"    
  ),
  forestryCastor = list(harvestBlockPriority = " age DESC ", 
                        reportHarvestConstraints = F
  ),
  blockingCastor = list(blockMethod = 'pre',
                        patchZone = 'default',
                        patchVariation = 6),
  growingStockCastor = list (periodLength = 10,
                             maxYieldAge = 250)
)